- https://nijianmo.github.io/amazon/index.html
- https://jmcauley.ucsd.edu/data/amazon/ 
- https://colab.research.google.com/drive/1Zv6MARGQcrBbLHyjPVVMZVnRWsRnVMpV

In [1]:
prfx = 'prep_20210307A1'

# get data

    download from http://localhost:8080/notebooks/git/product-category/notebooks/secrets_get_amazon_data.ipynb

In [2]:
import pandas as pd
import gzip
import json

In [3]:
pdata = "/data/git/product-category/data/amazon_meta_data"
!ls -hl {pdata}

total 13G
-rw-rw-r-- 1 ubuntu ubuntu   30M Dec  2 00:07 meta_AMAZON_FASHION.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  9.6M Aug  7  2020 meta_All_Beauty.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   57M Aug  7  2020 meta_Appliances.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   57M Aug  7  2020 meta_Appliances.json.gz.1
-rw-rw-r-- 1 ubuntu ubuntu  125M Aug  7  2020 meta_Arts_Crafts_and_Sewing.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.5G Aug  7  2020 meta_Automotive.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Books.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Books.json.gz.1
-rw-rw-r-- 1 ubuntu ubuntu  153M Aug  7  2020 meta_CDs_and_Vinyl.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  333M Aug  7  2020 meta_Cell_Phones_and_Accessories.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.5G Dec  2 00:18 meta_Clothing_Shoes_and_Jewelry.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   12M Aug  7  2020 meta_Digital_Music.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Electronics.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  372K Aug  7  2020 meta_Gift_Cards.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  102M Aug  7  2020 meta_Grocery_and_Gourmet_Food.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.7G Aug  7  2020 meta_Home_and_Kitchen.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   79M Aug  7  2020 meta_Industrial_and_Scientific.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   96M Aug  7  2020 meta_Kindle_Store.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  7.1M Aug  7  2020 meta_Luxury_Beauty.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2M Aug  7  2020 meta_Magazine_Subscriptions.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  100M Aug  7  2020 meta_Movies_and_TV.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  163M Aug  7  2020 meta_Musical_Instruments.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  485M Aug  7  2020 meta_Office_Products.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  399M Aug  7  2020 meta_Patio_Lawn_and_Garden.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  269M Aug  7  2020 meta_Pet_Supplies.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  4.9M Aug  7  2020 meta_Prime_Pantry.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   15M Aug  7  2020 meta_Software.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  490M Aug  7  2020 meta_Sports_and_Outdoors.json.gz
-rw-rw-r-- 1 ubuntu ubuntu 1008M Aug  7  2020 meta_Tools_and_Home_Improvement.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  763M Aug  7  2020 meta_Toys_and_Games.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   50M Aug  7  2020 meta_Video_Games.json.gz

In [4]:
fnms = !ls {pdata}
fnms = [o for o in fnms if o.endswith('.json.gz')]
fnms

['meta_AMAZON_FASHION.json.gz',
 'meta_All_Beauty.json.gz',
 'meta_Appliances.json.gz',
 'meta_Arts_Crafts_and_Sewing.json.gz',
 'meta_Automotive.json.gz',
 'meta_Books.json.gz',
 'meta_CDs_and_Vinyl.json.gz',
 'meta_Cell_Phones_and_Accessories.json.gz',
 'meta_Clothing_Shoes_and_Jewelry.json.gz',
 'meta_Digital_Music.json.gz',
 'meta_Electronics.json.gz',
 'meta_Gift_Cards.json.gz',
 'meta_Grocery_and_Gourmet_Food.json.gz',
 'meta_Home_and_Kitchen.json.gz',
 'meta_Industrial_and_Scientific.json.gz',
 'meta_Kindle_Store.json.gz',
 'meta_Luxury_Beauty.json.gz',
 'meta_Magazine_Subscriptions.json.gz',
 'meta_Movies_and_TV.json.gz',
 'meta_Musical_Instruments.json.gz',
 'meta_Office_Products.json.gz',
 'meta_Patio_Lawn_and_Garden.json.gz',
 'meta_Pet_Supplies.json.gz',
 'meta_Prime_Pantry.json.gz',
 'meta_Software.json.gz',
 'meta_Sports_and_Outdoors.json.gz',
 'meta_Tools_and_Home_Improvement.json.gz',
 'meta_Toys_and_Games.json.gz',
 'meta_Video_Games.json.gz']

In [5]:
domains = [o.strip('meta_').strip('.json.gz') for o in fnms]
dmn2fnm = dict(zip(domains, fnms))
dmn2fnm

{'AMAZON_FASHION': 'meta_AMAZON_FASHION.json.gz',
 'All_Beauty': 'meta_All_Beauty.json.gz',
 'Appliance': 'meta_Appliances.json.gz',
 'Arts_Crafts_and_Sewi': 'meta_Arts_Crafts_and_Sewing.json.gz',
 'Automotive': 'meta_Automotive.json.gz',
 'Book': 'meta_Books.json.gz',
 'CDs_and_Vinyl': 'meta_CDs_and_Vinyl.json.gz',
 'Cell_Phones_and_Accessorie': 'meta_Cell_Phones_and_Accessories.json.gz',
 'Clothing_Shoes_and_Jewelry': 'meta_Clothing_Shoes_and_Jewelry.json.gz',
 'Digital_Music': 'meta_Digital_Music.json.gz',
 'Electronic': 'meta_Electronics.json.gz',
 'Gift_Card': 'meta_Gift_Cards.json.gz',
 'Grocery_and_Gourmet_Food': 'meta_Grocery_and_Gourmet_Food.json.gz',
 'Home_and_Kitche': 'meta_Home_and_Kitchen.json.gz',
 'Industrial_and_Scientific': 'meta_Industrial_and_Scientific.json.gz',
 'Kindle_Store': 'meta_Kindle_Store.json.gz',
 'Luxury_Beauty': 'meta_Luxury_Beauty.json.gz',
 'Magazine_Subscripti': 'meta_Magazine_Subscriptions.json.gz',
 'Movies_and_TV': 'meta_Movies_and_TV.json.gz',
 'Musical_Instrument': 'meta_Musical_Instruments.json.gz',
 'Office_Product': 'meta_Office_Products.json.gz',
 'Patio_Lawn_and_Garde': 'meta_Patio_Lawn_and_Garden.json.gz',
 'Pet_Supplie': 'meta_Pet_Supplies.json.gz',
 'Prime_Pantry': 'meta_Prime_Pantry.json.gz',
 'Software': 'meta_Software.json.gz',
 'Sports_and_Outdoor': 'meta_Sports_and_Outdoors.json.gz',
 'Tools_and_Home_Improvement': 'meta_Tools_and_Home_Improvement.json.gz',
 'Toys_and_Game': 'meta_Toys_and_Games.json.gz',
 'Video_Game': 'meta_Video_Games.json.gz'}

In [6]:
KEYS2USE = set(['category', 'description', 'title', 'brand', 'feature', 'asin'])

In [7]:
# https://colab.research.google.com/drive/1Zv6MARGQcrBbLHyjPVVMZVnRWsRnVMpV#scrollTo=7igYuRaV4bF7
    
### load the meta data
def get_meta_data(domain, nrows=None):
    keys2use = KEYS2USE
    fnm = dmn2fnm[domain]
    data = []
    with gzip.open(f'{pdata}/{fnm}') as f:
        for i,l in enumerate(f):
            dat = json.loads(l.strip())
            dat = {k:v for k,v in dat.items() if k in keys2use}
            data.append(dat)
            if nrows and i>nrows: break

    # total length of list, this number equals total number of products
#     print("len(data)", len(data))

    # convert list into pandas dataframe
    df = pd.DataFrame.from_dict(data)
#     print("len(df)", len(df))

    ### remove rows with unformatted title (i.e. some 'title' may still contain html style content)
    df3 = df.fillna('')
    df4 = df3[df3.title.str.contains('getTime')] # unformatted rows
    df5 = df3[~df3.title.str.contains('getTime')] # filter those unformatted rows
#     print("len(df4)", len(df4))
#     print("len(df5)", len(df5))

    return df5

In [8]:
df = get_meta_data(domains[3], nrows=10000)
df.head(3)

,category,description,title,brand,feature,asin
0,"[Arts, Crafts & Sewing, Sewing, Trim & Embelli...",[The patch features the sweaty masculine hands...,You Son of a Bitch! 1987 Embroidered Patch,Honchosfx,[You son of a bitch patch - exclusive to Honch...,6665560953
1,"[Arts, Crafts & Sewing, Crafting, Paper & Pape...","[With 5 packs stars folding paper, each pack a...",Origami Stars Papers Package 1H (5 packs),,[],7000000376
2,"[Arts, Crafts & Sewing, Painting, Drawing & Ar...",[],Yi De Ge Chinese Calligraphy Sumi Drawing Blac...,MasterChinese,[],7000001089

for dmn in domains:
    df = get_meta_data(dmn, nrows=1000)
    print(dmn, df.shape)
    display(df.sample(5))

# preprocess data

## concate

In [9]:
dfs = []
for dmn in domains:
    print(dmn)
    df = get_meta_data(dmn, nrows=None)
    if set(df.columns)!= KEYS2USE: continue
    df = df[df.category.apply(len)>0]
    if len(df)==0: continue
    print(df.shape)
    df['domain'] = dmn
    display(df.sample(2))
    dfs.append(df)

AMAZON_FASHION
All_Beauty
Appliance
(29639, 6)

,category,description,title,brand,feature,asin,domain
19305,"[Appliances, Parts & Accessories, Refrigerator...",[This is a genuine replacement part. The model...,Frigidaire 218947201 Fill Tube Refrigerator,Frigidaire,"[Manufacturer Model #218947201, Genuine Replac...",B00M25GXRU,Appliance
3771,"[Appliances, Parts & Accessories, Refrigerator...",[Whirlpool Whirlpool Refrigerator Icemaker Ice...,Maytag Refrigerator Icemaker Ice Maker &amp; W...,Maytag,[Whirlpool- Genuine Replacement Part- Certifie...,B001TIWJQ0,Appliance

Arts_Crafts_and_Sewi
(284889, 6)

,category,description,title,brand,feature,asin,domain
69137,"[Arts, Crafts & Sewing, Sewing, Trim & Embelli...",[C&D VISIONARY INC-C&D Visionary Iron-On Patch...,Application Giraffe Patch,Application,"[Iron-On or Sew to Any Garment, Top Quality, D...",B005P1XBGE,Arts_Crafts_and_Sewi
252968,"[Arts, Crafts & Sewing, Sewing, Sewing Notions...","[Sizes: 60mm(2 3/8"") X 60mm(2 3/8"")<br> Quanti...",Bluemoona 20 PCS - Empty Plastic Wire Spools B...,Sewing,"[Sizes: 60mm(2 3/8"") X 60mm(2 3/8""), Color: BL...",B014ZO9JXU,Arts_Crafts_and_Sewi

Automotive
(897587, 6)

,category,description,title,brand,feature,asin,domain
334538,"[Automotive, Replacement Parts, Filters, Air F...",[Clean air is critical to the performance and ...,Hastings Filters AF1453 Panel Air Filter Element,Hastings Filters,[Fully meets filtration requirements of the ap...,B005NHHI1O,Automotive
246797,"[Automotive, Interior Accessories, Safety]","[A perfect complement to your office and home,...",Honda Logo Real Carbon Fiber Detachable Cap Ro...,"Au-Tomotive Gold, INC.",[custom designed pen features a black carbon f...,B003D11DTA,Automotive

Book
(2545520, 6)

,category,description,title,brand,feature,asin,domain
1123073,"[Books, Religion & Spirituality, Occult & Para...",[Nathaniel Friedland field-tested his practica...,Be Psychic Now!,Visit Amazon's Nathaniel Friedland Page,[],0967666902,Book
368961,"[Books, Cookbooks, Food &amp; Wine, Regional &...","[, <strong>Product Description</strong><br />,...",New American Table,Visit Amazon's Marcus Samuelsson Page,[],047028188X,Book

CDs_and_Vinyl
(516914, 6)

,category,description,title,brand,feature,asin,domain
58050,"[CDs & Vinyl, Rock, Hard Rock]",[],Capricorn,Mike Tramp,[],B0000061QZ,CDs_and_Vinyl
188890,"[CDs & Vinyl, Dance & Electronic, Electronica]",[],"Party Keller, Vol. 1",Florian Keller,[],B00028F8D4,CDs_and_Vinyl

Cell_Phones_and_Accessorie
(534466, 6)

,category,description,title,brand,feature,asin,domain
281974,"[Cell Phones & Accessories, Cases, Holsters & ...",[This TPU skin case fits your phone like a glo...,Black Jellyfish Tpu Gel Case Cover For The LG ...,Think Mobile,"[Fully protects your device, and keeps it safe...",B00LX1UHO4,Cell_Phones_and_Accessorie
293260,"[Cell Phones & Accessories, Accessories, Charg...",[],CiDoss 7 in 1 10ft 3M Long 30pin USB Data Sync...,,[],B00MVQ1VUE,Cell_Phones_and_Accessorie

Clothing_Shoes_and_Jewelry
(2665580, 6)

,category,description,title,brand,feature,asin,domain
2433459,"[Clothing, Shoes & Jewelry, Women, Handbags & ...",[This Continental Clutch Wallet from Dooney & ...,Dooney & Bourke Womens Croco Leather Continent...,Dooney & Bourke,"[Imported, Constructed from croc embossed leat...",B01BT34KBQ,Clothing_Shoes_and_Jewelry
2392500,"[Clothing, Shoes & Jewelry, Women, Jewelry, Ea...",[These pretty stud earrings feature 6mm london...,Bria Lou 14k Gold Round-Cut Genuine Natural or...,Bria Lou,[LUXURY ELEGANT DESIGN - Stunning 6mm Gemstone...,B01AVHFB96,Clothing_Shoes_and_Jewelry

Digital_Music
(7, 6)

,category,description,title,brand,feature,asin,domain
35678,"[Digital Music, Blues, Electric Blues Guitar]",[Shinybow VGA/AUDIO Receiver: SB-6110R\n\nA co...,Shinybow VGA Video + Audio CAT5 Receiver SB-6110R,Shinybow,[VGA RGBHV Video and Audio CAT5 Receiver with ...,B0013BM5T4,Digital_Music
61265,"[Digital Music, Alternative Rock]",[],"<span id=""parentalAdvisory"" class=""a-size-medi...",Roddy Hart & the Lonesome Fire,[],B00E668TKM,Digital_Music

Electronic
(786445, 6)

,category,description,title,brand,feature,asin,domain
520202,"[Electronics, Computers & Accessories, Laptop ...",[],TopCase 3 in 1 Bundle - Chevron Series Rubberi...,CulaLuva,[],B00LW7JC3G,Electronic
51468,"[Electronics, Accessories & Supplies, Telephon...",[],Sony Ericsson Common Products Handsfree Headse...,Sony Ericsson,[Works with the following phones: Sony Ericsso...,B0000AKALT,Electronic

Gift_Card
(1542, 6)

,category,description,title,brand,feature,asin,domain
1108,"[Gift Cards, Gift Cards]",[The Cheesecake Factory offers more than 200 m...,The Cheesecake Factory Pumpkin Pecan Cheeseca...,,[],B00O5C6C4W,Gift_Card
275,"[Gift Cards, Gift Cards]",[Some have a gift for great food. Others would...,Ruby Tuesday Gift Card,Ruby Tuesday,[Redeemable at Ruby Tuesdays in the continenta...,B006PJHPV2,Gift_Card

Grocery_and_Gourmet_Food
(287051, 6)

,category,description,title,brand,feature,asin,domain
135461,"[Grocery & Gourmet Food, Beverages, Coffee, Te...",[],"Peace Tea, Caddy Shack Tea + Lemonade, 23 Ounc...",Peace Tea,[],B00BJHENUG,Grocery_and_Gourmet_Food
218398,"[Grocery & Gourmet Food, Candy & Chocolate, Ca...",[Sconza 70 Percent Cacao Dark Chocolate Toffee...,Sconza 70 Percent Cacao Dark Chocolate Toffee ...,Sconza,[],B00OD4V7K6,Grocery_and_Gourmet_Food

Home_and_Kitche
(1300540, 6)

,category,description,title,brand,feature,asin,domain
543534,"[Home & Kitchen, Kitchen & Dining, Kitchen Ute...",[This sleek ACCT digital scale features a larg...,2000g X 0.1g Digital Precision Scale with Tray...,Horizon,"[Large non-magnetic stainless steel platform, ...",B00CNE6FFA,Home_and_Kitche
650902,"[Home & Kitchen, Event & Party Supplies, Decor...",[],20 Pcs Chinese Sky Fly Fire Paper Lanterns Wis...,,[],B00GLMYFO8,Home_and_Kitche

Industrial_and_Scientific
(159350, 6)

,category,description,title,brand,feature,asin,domain
57150,"[Industrial & Scientific, Industrial Electrica...","[<ul><li>Feature:2W Rated Power, 1K Ohm Resist...",uxcell WXD3-13 1K Ohm 2W Watt Rotary Wirewound...,uxcell,[],B008DEYJFW,Industrial_and_Scientific
27709,"[Industrial & Scientific, Lab & Scientific Pro...","[<div class=""aplus"">, This Wheaton Boston roun...","Wheaton 223738 Serum Bottle 5mL, Clear Borosil...",Wheaton,[],B003FSTUU0,Industrial_and_Scientific

Kindle_Store
(491670, 6)

,category,description,title,brand,feature,asin,domain
417488,"[Kindle Store, Kindle eBooks, Self-Help]",[],Pain - Kindle edition,Angela D.,[],B0160LIKOU,Kindle_Store
324102,"[Kindle Store, Kindle eBooks, Science Fiction ...",[],Flight for the Ancients (The Phoenix Chronicl...,Visit Amazon's Kris Powers Page,[],B00PVQY6DA,Kindle_Store

Luxury_Beauty
Magazine_Subscripti
(2883, 6)

,category,description,title,brand,feature,asin,domain
2688,"[Magazine Subscriptions, Entertainment & Pop C...",[Nobody knows more about star power than Vanit...,"<span class=""a-size-medium a-color-secondary""",Conde Nast,[],B00D8GWHXG,Magazine_Subscripti
1815,"[Magazine Subscriptions, Crafts & Hobbies, Qui...",[Find the secrets for creating beautiful quilt...,"<span class=""a-size-medium a-color-secondary""","F+W Subscription Services, LLC",[],B00007B0Z3,Magazine_Subscripti

Movies_and_TV
(203541, 6)

,category,description,title,brand,feature,asin,domain
51496,"[Movies & TV, BBC, All BBC Titles]","[<![CDATA[, Blue Planet Seas of Life: Tidal Se...","The Blue Planet - Seas Of Life, Part 4 - Tidal...",,[],B00005YU7J,Movies_and_TV
140023,"[Movies & TV, Blu-ray, Movies]","[Sweden released, Blu-Ray/Region A/B/C : it WI...",Rovdyr Blue-ray,Henriette Bruusgaard,[],B003VHUHHA,Movies_and_TV

Musical_Instrument
(114397, 6)

,category,description,title,brand,feature,asin,domain
81075,"[Musical Instruments, Live Sound & Stage, Ligh...",[<b>What's in the Package</b> <br /> 1 x Produ...,1byone Stage Light Disco DJ Colorful Sound Act...,1byone,[This disco light can absolutely shock your ey...,B00GN4UTXA,Musical_Instrument
28147,"[Musical Instruments, Amplifiers & Effects, Gu...",[The Aura Dreadnought acoustic guitar Imaging ...,Fishman Aura Dreadnought Acoustic Guitar Imagi...,Fishman,"[Volume, Blend, and Image Select controls, Eli...",B000ZJWHUW,Musical_Instrument

Office_Product
(298876, 6)

,category,description,title,brand,feature,asin,domain
55728,"[Office Products, Office & School Supplies, Ta...",[Tombow MONO Glue Sticks are a necessity for e...,"Tombow MONO Glue Sticks, 0.28 oz. Each, 2-Pack...",Tombow,"[2-pack, small enough to fit in pencil pouch, ...",B001DXMRUO,Office_Product
266754,"[Office Products, Office & School Supplies, St...",[Vinyl banners can be used to make a statement...,Eyelash Extension 13 oz Vinyl Banner Sign w/ M...,Fastasticdeals,[High quality heavy duty 13 oz vinyl indoor /o...,B013MV94FA,Office_Product

Patio_Lawn_and_Garde
(279456, 6)

,category,description,title,brand,feature,asin,domain
183865,"[Patio, Lawn & Garden, Patio Furniture & Acces...",[The morning cup of coffee or the afternoon cu...,3 Piece Outdoor Bistro Set Bar Height -Black. ...,Woodard,[Classically styled 3-piece bar height outdoor...,B00NEB9YWM,Patio_Lawn_and_Garde
262719,"[Patio, Lawn & Garden, Outdoor Dcor, Garden Sc...",[fairy gardens are a miniaturized garden you b...,Home Fashion Rustic Fairy Garden Fairy Door Re...,Home Fashion,"[Made of Polyresin, This product measures h: 4...",B01DEVHCCK,Patio_Lawn_and_Garde

Pet_Supplie
(189454, 6)

,category,description,title,brand,feature,asin,domain
97461,"[Pet Supplies, Dogs, Treats, Rawhide]",[Until doggie dentists invent a toothbrush tha...,Ushide Natural Knotted Bone,USHIDE,"[Made In The Usa, Contains No Bleach, Guarante...",B00BEHQZO8,Pet_Supplie
41761,"[Pet Supplies, Birds, Toys]",[The Brainy Bird Teenies Series Toys are made ...,Brainy Bird Teenies Series Toy Tower,Brainy Bird,[Entertains small and medium-sized birds for h...,B001MUPGTC,Pet_Supplie

Prime_Pantry
Software
(24727, 6)

,category,description,title,brand,feature,asin,domain
1288,"[Software, Programming & Web Development, Data...",[Phyla is the first true object-oriented datab...,Phyla 1.0,Mainstay,[],B00002S7VA,Software
1477,"[Software, Education & Reference, Languages]","[Now you can learn seven languages (Spanish, F...",Rosetta Stone: PowerPac,Fairfield Language Technologies,[],B00002S9FF,Software

Sports_and_Outdoor
(893979, 6)

,category,description,title,brand,feature,asin,domain
500303,"[Sports & Outdoors, Sports & Fitness, Exercise...","[Most athletes, trainers and fitness enthusias...",Surge Fitness Trainer with Workout,Surge,[Patented dual handles allow hundreds of diffe...,B00FK7T248,Sports_and_Outdoor
402952,"[Sports & Outdoors, Sports & Fitness, Airsoft ...",[This Deluxe 2 Valve Fill Station has a full 4...,WaveToGo Paintball CO2 Fill Station Refill Dua...,WaveToGo,"[40 Inch Stainless Steel Dual Braided Hose, He...",B00AYP6GKY,Sports_and_Outdoor

Tools_and_Home_Improvement
(544118, 6)

,category,description,title,brand,feature,asin,domain
8141,"[Tools & Home Improvement, Electrical, Switche...",[Control holiday lights automatically by plugg...,Ingraham Outdoor Countdown Timer,Salton,"[8 timed settings, All weather case, Heavy dut...",B00013K2Q8,Tools_and_Home_Improvement
5206,"[Tools & Home Improvement, Power & Hand Tools,...",[Double tooth for longer life and improved dur...,DEWALT D180044 2-3/4-Inch Hole Saw,DEWALT,"[The product is 2-3/4"" 70MM Bi Hole Saw, Easy ...",B00005LEZI,Tools_and_Home_Improvement

Toys_and_Game
(571640, 6)

,category,description,title,brand,feature,asin,domain
187903,"[Toys & Games, Sports & Outdoor Play, Bubbles]","[Bubble Fish Look, listen, feel and pour! Ple...",Ambi Bubble Fish,Ambi Toys,"[The essential toy for bath time fun., This co...",B004M8ROI2,Toys_and_Game
354823,"[Toys & Games, Baby & Toddler Toys, Music & So...",[Play & Discover with this educational toy Col...,PlayGo First Discoveries Toy,PlayGo,[Watch your baby enjoy and discover a variety ...,B00EVY1NRA,Toys_and_Game

Video_Game
(82394, 6)

,category,description,title,brand,feature,asin,domain
52605,"[Video Games, Wii, Accessories, Cables & Adapt...",[Extends the effective range of your console t...,2x 6FT Controller Extension Cable For Wii Game...,by\n \n KMD,[Extends the effective range of your console t...,B005SN8HFO,Video_Game
48962,"[Video Games, PC, Games, </span></span></span>]","[<div>, Princess Jessa, along with the loyal k...",Shining in the Darkness [Download],by\n \n Sega,[],B004J4WZI8,Video_Game

In [10]:
df = pd.concat(dfs)
df.shape

(13706665, 7)

In [11]:
df.sample(3)

,category,description,title,brand,feature,asin,domain
1526888,"[Clothing, Shoes & Jewelry, Luggage & Travel G...",[300d polyester duffle color blocked with soli...,Billabong Men's Sierra Grands Duffle,,"[100% Polyester, Imported, Zipper closure, 30""...",B00N9RD7FQ,Clothing_Shoes_and_Jewelry
662035,"[Automotive, Replacement Parts, Transmission &...",[],Genuine Honda 46971-SR3-A00 Clutch Master Cyli...,Honda,"[Del Sol '93-97, Genuine OEM, Direct fit, Genu...",B00LIUKAH4,Automotive
100280,"[Musical Instruments, Microphones & Accessorie...","[<br>Special design for chatting over QQ, MSN,...",Vktech&reg; Super USB 2.0 Condenser Microphone...,Vktech,"[Special design for chatting over QQ, MSN, SKY...",B00UV7CZP0,Musical_Instrument

## cleanup

### category

In [12]:
%%time
def try2eval(x):
    try:
        x = eval(x)
        x = (o.replace('|','') for o in x)
        return '|'.join(x)
    except SyntaxError:
        return ""

df.category = df.category.astype(str)
df.category = df.category.apply(try2eval)
print("df.shape:", df.shape)

df.shape: (13706665, 7)
CPU times: user 3min 36s, sys: 4.95 s, total: 3min 41s
Wall time: 3min 40s

### text

In [13]:
import re

def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

In [14]:
%%time
df.fillna('', inplace=True)

for col in ['description', 'feature']:
    df[col] = df[col].apply(lambda x: "\n".join(x) if len(x) else "")

for col in ['description', 'title', 'brand', 'feature',]:
    df[col] = df[col].apply(cleanhtml)

CPU times: user 3min 20s, sys: 4.94 s, total: 3min 25s
Wall time: 3min 25s

### truncate

In [15]:
import numpy as np
for col in ['description', 'title', 'brand', 'feature',]:
    leng = df[col].apply(len)
    print(col, np.percentile(leng, 95))

description 1666.0
title 145.0
brand 34.0
feature 754.0

In [16]:
def trunc(x): return x[:1000]

In [17]:
%%time
df['txt'] = df.title.apply(trunc) + " " + df.brand.apply(trunc) + " " + df.description.apply(trunc) + " " + df.feature.apply(trunc)

CPU times: user 50.9 s, sys: 11.9 s, total: 1min 2s
Wall time: 1min 10s

In [18]:
leng = df.txt.apply(len)
print(leng.max(), np.percentile(leng, 95))

3113 1536.0

# train val split

In [19]:
import numpy as np

np.random.seed(101)
df['is_validation'] = np.random.choice(2, size=len(df), p=[0.85,0.15])

In [20]:
df.is_validation.value_counts()

0    11649852
1     2056813
Name: is_validation, dtype: int64

In [21]:
df.sample(3)

,category,description,title,brand,feature,asin,domain,txt,is_validation
173884,CDs & Vinyl|Alternative Rock|New Wave & Post-P...,VARIOUS ARTISTS - 1980S: MODERN ROCK OF THE 80...,Hardest Hits: Modern Rock of the 80's,Various Artists,,B00009PXXA,CDs_and_Vinyl,Hardest Hits: Modern Rock of the 80's Various ...,0
1251629,"Clothing, Shoes & Jewelry|Women|Shoes|Boots|Kn...",The Aquatalia by Marvin K. collection is manuf...,Aquatalia Women's Helena Dress Boot,Aquatalia,100% Leather\nImported\nSynthetic sole\nShaft ...,B00ISSXHZG,Clothing_Shoes_and_Jewelry,Aquatalia Women's Helena Dress Boot Aquatalia ...,0
934399,"Clothing, Shoes & Jewelry|Women|Contemporary &...",Enjoy all-star footwear from one of the most r...,kate spade new york Women's Cris Pump,,100% Leather\nImported\nLeather sole\nHeel mea...,B00DSLK594,Clothing_Shoes_and_Jewelry,kate spade new york Women's Cris Pump Enjoy a...,0

# save

In [22]:
%%time
df.to_csv(f'../data/data__{prfx}.csv', index=False)

CPU times: user 9min 42s, sys: 38.6 s, total: 10min 20s
Wall time: 10min 21s

In [23]:
ls -hl ../data/data__{prfx}.csv

-rw-rw-r-- 1 ubuntu ubuntu 20G Mar  7 15:35 ../data/data__prep_20210307A1.csv

## make a sample

In [24]:
import numpy as np
np.random.seed(101)
df_sample = df.sample(10000)

In [25]:
df_sample.to_csv(f'../data/data_sample__{prfx}.csv', index=False)

## make more samples

In [51]:
%%time
df = pd.read_csv(f'../data/data__{prfx}.csv', error_bad_lines=False)

b'Skipping line 2057200: expected 9 fields, saw 22\n'

KeyboardInterrupt:

In [52]:
df.shape

(1000000, 9)

In [43]:
df.sample().txt.values

array(['Carl Pencil Sharpener CC-2000 Red Carl Pencil Brand Karujimu-ki \nProduct Number A5PR-R \nLong-life products that continue to use a long time color red. Cutting instrument pencil functional timeless durable. \nClassic body of sheet metal working, I was stuck in the texture and color. \nBody sheet metal products. Rubber chuck use without the scratches in pencil. \nBlade sharpener made in Japan. \nCommodity Description \nThe durable, and fully renewable, it is beautiful pencil sharpener using material of ultimate returns to the soil all the "iron" in the end. In addition, the part that sandwich to avoid scratching the surface of the pencil sharpening, use a chuck of rubber to hold firmly soft. It was made up of special steel, along with the blade, keeping long-term high functionality sharpener is superior in accuracy and durability. . .  I am using another product color in some detail image. . Size: thickness = 132mm Vertical Horizontal = 75mm = 125mm. Item color trend: red. . 12.5cmX7.5cmX13.2cm'],
      dtype=object)

In [28]:
np.random.seed(101)
for sz in (int(o) for o in (1e4, 1e5, 5e5, 1e6, 5e6)):
    df_sample = df.sample(sz)
    df_sample.to_csv(f'../data/data_sample_{sz}__{prfx}.csv', index=False)

KeyboardInterrupt: