- https://nijianmo.github.io/amazon/index.html
- https://jmcauley.ucsd.edu/data/amazon/ 
- https://colab.research.google.com/drive/1Zv6MARGQcrBbLHyjPVVMZVnRWsRnVMpV

In [1]:
prfx = 'prep_20210304A1'

# get data

    download from http://localhost:8080/notebooks/git/product-category/notebooks/secrets_get_amazon_data.ipynb

In [2]:
import pandas as pd
import gzip
import json

In [3]:
pdata = "/data/git/product-category/data/amazon_meta_data"
!ls -hl {pdata}

total 13G
-rw-rw-r-- 1 ubuntu ubuntu   30M Dec  2 00:07 meta_AMAZON_FASHION.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  9.6M Aug  7  2020 meta_All_Beauty.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   57M Aug  7  2020 meta_Appliances.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   57M Aug  7  2020 meta_Appliances.json.gz.1
-rw-rw-r-- 1 ubuntu ubuntu  125M Aug  7  2020 meta_Arts_Crafts_and_Sewing.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.5G Aug  7  2020 meta_Automotive.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Books.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Books.json.gz.1
-rw-rw-r-- 1 ubuntu ubuntu  153M Aug  7  2020 meta_CDs_and_Vinyl.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  333M Aug  7  2020 meta_Cell_Phones_and_Accessories.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.5G Dec  2 00:18 meta_Clothing_Shoes_and_Jewelry.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   12M Aug  7  2020 meta_Digital_Music.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Electronics.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  372K Aug  7  2020 meta_Gift_Cards.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  102M Aug  7  2020 meta_Grocery_and_Gourmet_Food.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.7G Aug  7  2020 meta_Home_and_Kitchen.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   79M Aug  7  2020 meta_Industrial_and_Scientific.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   96M Aug  7  2020 meta_Kindle_Store.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  7.1M Aug  7  2020 meta_Luxury_Beauty.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2M Aug  7  2020 meta_Magazine_Subscriptions.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  100M Aug  7  2020 meta_Movies_and_TV.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  163M Aug  7  2020 meta_Musical_Instruments.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  485M Aug  7  2020 meta_Office_Products.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  399M Aug  7  2020 meta_Patio_Lawn_and_Garden.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  269M Aug  7  2020 meta_Pet_Supplies.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  4.9M Aug  7  2020 meta_Prime_Pantry.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   15M Aug  7  2020 meta_Software.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  490M Aug  7  2020 meta_Sports_and_Outdoors.json.gz
-rw-rw-r-- 1 ubuntu ubuntu 1008M Aug  7  2020 meta_Tools_and_Home_Improvement.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  763M Aug  7  2020 meta_Toys_and_Games.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   50M Aug  7  2020 meta_Video_Games.json.gz

In [4]:
fnms = !ls {pdata}
fnms = [o for o in fnms if o.endswith('.json.gz')]
fnms

['meta_AMAZON_FASHION.json.gz',
 'meta_All_Beauty.json.gz',
 'meta_Appliances.json.gz',
 'meta_Arts_Crafts_and_Sewing.json.gz',
 'meta_Automotive.json.gz',
 'meta_Books.json.gz',
 'meta_CDs_and_Vinyl.json.gz',
 'meta_Cell_Phones_and_Accessories.json.gz',
 'meta_Clothing_Shoes_and_Jewelry.json.gz',
 'meta_Digital_Music.json.gz',
 'meta_Electronics.json.gz',
 'meta_Gift_Cards.json.gz',
 'meta_Grocery_and_Gourmet_Food.json.gz',
 'meta_Home_and_Kitchen.json.gz',
 'meta_Industrial_and_Scientific.json.gz',
 'meta_Kindle_Store.json.gz',
 'meta_Luxury_Beauty.json.gz',
 'meta_Magazine_Subscriptions.json.gz',
 'meta_Movies_and_TV.json.gz',
 'meta_Musical_Instruments.json.gz',
 'meta_Office_Products.json.gz',
 'meta_Patio_Lawn_and_Garden.json.gz',
 'meta_Pet_Supplies.json.gz',
 'meta_Prime_Pantry.json.gz',
 'meta_Software.json.gz',
 'meta_Sports_and_Outdoors.json.gz',
 'meta_Tools_and_Home_Improvement.json.gz',
 'meta_Toys_and_Games.json.gz',
 'meta_Video_Games.json.gz']

In [3]:
domains = [o.strip('meta_').strip('.json.gz') for o in fnms]
dmn2fnm = dict(zip(domains, fnms))
dmn2fnm

total 13G
-rw-rw-r-- 1 ubuntu ubuntu   30M Dec  2 00:07 meta_AMAZON_FASHION.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  9.6M Aug  7  2020 meta_All_Beauty.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   57M Aug  7  2020 meta_Appliances.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   57M Aug  7  2020 meta_Appliances.json.gz.1
-rw-rw-r-- 1 ubuntu ubuntu  125M Aug  7  2020 meta_Arts_Crafts_and_Sewing.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.5G Aug  7  2020 meta_Automotive.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Books.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Books.json.gz.1
-rw-rw-r-- 1 ubuntu ubuntu  153M Aug  7  2020 meta_CDs_and_Vinyl.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  333M Aug  7  2020 meta_Cell_Phones_and_Accessories.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.5G Dec  2 00:18 meta_Clothing_Shoes_and_Jewelry.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   12M Aug  7  2020 meta_Digital_Music.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2G Aug  7  2020 meta_Electronics.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  372K Aug  7  2020 meta_Gift_Cards.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  102M Aug  7  2020 meta_Grocery_and_Gourmet_Food.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.7G Aug  7  2020 meta_Home_and_Kitchen.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   79M Aug  7  2020 meta_Industrial_and_Scientific.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   96M Aug  7  2020 meta_Kindle_Store.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  7.1M Aug  7  2020 meta_Luxury_Beauty.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  1.2M Aug  7  2020 meta_Magazine_Subscriptions.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  100M Aug  7  2020 meta_Movies_and_TV.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  163M Aug  7  2020 meta_Musical_Instruments.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  485M Aug  7  2020 meta_Office_Products.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  399M Aug  7  2020 meta_Patio_Lawn_and_Garden.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  269M Aug  7  2020 meta_Pet_Supplies.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  4.9M Aug  7  2020 meta_Prime_Pantry.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   15M Aug  7  2020 meta_Software.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  490M Aug  7  2020 meta_Sports_and_Outdoors.json.gz
-rw-rw-r-- 1 ubuntu ubuntu 1008M Aug  7  2020 meta_Tools_and_Home_Improvement.json.gz
-rw-rw-r-- 1 ubuntu ubuntu  763M Aug  7  2020 meta_Toys_and_Games.json.gz
-rw-rw-r-- 1 ubuntu ubuntu   50M Aug  7  2020 meta_Video_Games.json.gz

{'AMAZON_FASHION': 'meta_AMAZON_FASHION.json.gz',
 'All_Beauty': 'meta_All_Beauty.json.gz',
 'Appliance': 'meta_Appliances.json.gz',
 'Arts_Crafts_and_Sewi': 'meta_Arts_Crafts_and_Sewing.json.gz',
 'Automotive': 'meta_Automotive.json.gz',
 'Book': 'meta_Books.json.gz',
 'CDs_and_Vinyl': 'meta_CDs_and_Vinyl.json.gz',
 'Cell_Phones_and_Accessorie': 'meta_Cell_Phones_and_Accessories.json.gz',
 'Clothing_Shoes_and_Jewelry': 'meta_Clothing_Shoes_and_Jewelry.json.gz',
 'Digital_Music': 'meta_Digital_Music.json.gz',
 'Electronic': 'meta_Electronics.json.gz',
 'Gift_Card': 'meta_Gift_Cards.json.gz',
 'Grocery_and_Gourmet_Food': 'meta_Grocery_and_Gourmet_Food.json.gz',
 'Home_and_Kitche': 'meta_Home_and_Kitchen.json.gz',
 'Industrial_and_Scientific': 'meta_Industrial_and_Scientific.json.gz',
 'Kindle_Store': 'meta_Kindle_Store.json.gz',
 'Luxury_Beauty': 'meta_Luxury_Beauty.json.gz',
 'Magazine_Subscripti': 'meta_Magazine_Subscriptions.json.gz',
 'Movies_and_TV': 'meta_Movies_and_TV.json.gz',
 'Musical_Instrument': 'meta_Musical_Instruments.json.gz',
 'Office_Product': 'meta_Office_Products.json.gz',
 'Patio_Lawn_and_Garde': 'meta_Patio_Lawn_and_Garden.json.gz',
 'Pet_Supplie': 'meta_Pet_Supplies.json.gz',
 'Prime_Pantry': 'meta_Prime_Pantry.json.gz',
 'Software': 'meta_Software.json.gz',
 'Sports_and_Outdoor': 'meta_Sports_and_Outdoors.json.gz',
 'Tools_and_Home_Improvement': 'meta_Tools_and_Home_Improvement.json.gz',
 'Toys_and_Game': 'meta_Toys_and_Games.json.gz',
 'Video_Game': 'meta_Video_Games.json.gz'}

In [4]:
KEYS2USE = set(['category', 'description', 'title', 'brand', 'feature', 'asin'])

In [5]:
# https://colab.research.google.com/drive/1Zv6MARGQcrBbLHyjPVVMZVnRWsRnVMpV#scrollTo=7igYuRaV4bF7
    
### load the meta data
def get_meta_data(domain, nrows=None):
    keys2use = KEYS2USE
    fnm = dmn2fnm[domain]
    data = []
    with gzip.open(f'{pdata}/{fnm}') as f:
        for i,l in enumerate(f):
            dat = json.loads(l.strip())
            dat = {k:v for k,v in dat.items() if k in keys2use}
            data.append(dat)
            if nrows and i>nrows: break

    # total length of list, this number equals total number of products
#     print("len(data)", len(data))

    # convert list into pandas dataframe
    df = pd.DataFrame.from_dict(data)
#     print("len(df)", len(df))

    ### remove rows with unformatted title (i.e. some 'title' may still contain html style content)
    df3 = df.fillna('')
    df4 = df3[df3.title.str.contains('getTime')] # unformatted rows
    df5 = df3[~df3.title.str.contains('getTime')] # filter those unformatted rows
#     print("len(df4)", len(df4))
#     print("len(df5)", len(df5))

    return df5

In [6]:
df = get_meta_data(domains[3], nrows=10000)
df.head(3)

,category,description,title,brand,feature,asin
0,"[Arts, Crafts & Sewing, Sewing, Trim & Embelli...",[The patch features the sweaty masculine hands...,You Son of a Bitch! 1987 Embroidered Patch,Honchosfx,[You son of a bitch patch - exclusive to Honch...,6665560953
1,"[Arts, Crafts & Sewing, Crafting, Paper & Pape...","[With 5 packs stars folding paper, each pack a...",Origami Stars Papers Package 1H (5 packs),,[],7000000376
2,"[Arts, Crafts & Sewing, Painting, Drawing & Ar...",[],Yi De Ge Chinese Calligraphy Sumi Drawing Blac...,MasterChinese,[],7000001089

for dmn in domains:
    df = get_meta_data(dmn, nrows=1000)
    print(dmn, df.shape)
    display(df.sample(5))

# preprocess data

## concate

In [7]:
dfs = []
for dmn in domains:
    print(dmn)
    df = get_meta_data(dmn, nrows=None)
    if set(df.columns)!= KEYS2USE: continue
    df = df[df.category.apply(len)>0]
    if len(df)==0: continue
    print(df.shape)
    df['domain'] = dmn
    display(df.sample(2))
    dfs.append(df)

AMAZON_FASHION
All_Beauty
Appliance
(29639, 6)

,category,description,title,brand,feature,asin,domain
14385,"[Appliances, Parts & Accessories, Refrigerator...",[CB10942 for GE WR55X10942 Refrigerator Defros...,Refrigerator Main Control Board for Ge Wr55x10...,GE,[Brand New! Refrigerator Control Board. Replac...,B00EYLZB78,Appliance
10273,"[Appliances, Parts & Accessories, Refrigerator...",[This blower wheel will replace a worn or dama...,Whirlpool 53-0106 Blower Wheel,Whirlpool,"[Manufactured to fit a 1/2-Inch motor shaft, C...",B00A8O07ME,Appliance

Arts_Crafts_and_Sewi
(284889, 6)

,category,description,title,brand,feature,asin,domain
30301,"[Arts, Crafts & Sewing, Painting, Drawing & Ar...",[Art Advantage mini easel oil paint set. Set c...,Art Advantage Mini Easel Oil Paint Set,Art Advantage,"[Oil paint set, Comes with a table easel, One ...",B0027A39CC,Arts_Crafts_and_Sewi
162949,"[Arts, Crafts & Sewing, Knitting & Crochet, Kn...",[Ultra Sponge Bar (Needle Retainer) Strip for ...,NEW Adhesive Back Sponge for Brother/Singer/St...,Ultra Sponge Bar Strip,"[Made in the USA, Fits standard & bulky gauge ...",B00INHVJ34,Arts_Crafts_and_Sewi

Automotive
(897587, 6)

,category,description,title,brand,feature,asin,domain
422771,"[Automotive, Tools & Equipment]",[Dorman is a leading supplier of original equi...,"Dorman 49051 Multi Use Removal Tool Set, 5 Piece",Dorman,"[Kit includes a wide edge remover, narrow edge...",B008ZCGZUY,Automotive
785230,"[Automotive, Motorcycle & Powersports, Protect...",[The Viking Cycle Warlock Motorcycle Mesh Jack...,Viking Cycle Motorcycle Jacket for Men,Viking Cycle,"[Hand wash, Cooling mesh shell that covers; to...",B00Y1Q3U92,Automotive

Book
(2545520, 6)

,category,description,title,brand,feature,asin,domain
2423185,"[Books, Literature &amp; Fiction, Literary]",[J.S. Scott is a New York Times and USA Today ...,Billionaire Undone: The Billionaire's Obsessio...,Visit Amazon's J. S. Scott Page,[],193996248X,Book
831689,"[Books, Crafts, Hobbies &amp; Home, Antiques &...","[Text: English, German (translation), , ]",The History of Modern Furniture (English and G...,Visit Amazon's Karl Mang Page,[],0810910667,Book

CDs_and_Vinyl
(516914, 6)

,category,description,title,brand,feature,asin,domain
7907,"[CDs & Vinyl, Classical, Chamber Music]",[LASZLO KOVACS - BEST OF OPERETTA VOL. 2 - CD],Best of Operetta 2 / Various,VARIOUS ARTISTS,[],B0000014CG,CDs_and_Vinyl
483059,"[CDs & Vinyl, Classical]",[Following the rebirth of the Erato label in 2...,"Beethoven : Piano Sonatas No.7, No.14, 'Moonli...",Nicola Lugansky,[],B00I5OZ1VG,CDs_and_Vinyl

Cell_Phones_and_Accessorie
(534466, 6)

,category,description,title,brand,feature,asin,domain
206353,"[Cell Phones & Accessories, Cases, Holsters & ...",[],HTC Desire 601 British Blue Police Box Phone C...,TrekCovers,[],B00GG1J3AA,Cell_Phones_and_Accessorie
563567,"[Cell Phones & Accessories, Cases, Holsters & ...",[<b>xhorizon Premium Leather Folio Case [Walle...,"Case for Samsung S7 Edge,xhorizon TM FL8 Premi...",xhorizon,[Details of the wallet case cover:100% brand n...,B01EY0OOD0,Cell_Phones_and_Accessorie

Clothing_Shoes_and_Jewelry
(2665580, 6)

,category,description,title,brand,feature,asin,domain
2160464,"[Clothing, Shoes & Jewelry, Women, Shoes, Slip...",[Toggle Trim Full Collar Slipper. Extra Comfor...,Sleepers Womens/Ladies Tanya Toggle Trim Full ...,Sleepers,"[Mixed, ,, Toggle Trim Full Collar Slipper., E...",B015GNAJJW,Clothing_Shoes_and_Jewelry
2397006,"[Clothing, Shoes & Jewelry, Novelty & More, Cl...",[Very soft and breathable thong made from micr...,Emporio Armani Men's Basic Microfiber Thong,,[Package Dimensions:\n \n19...,B01AY1WK34,Clothing_Shoes_and_Jewelry

Digital_Music
(7, 6)

,category,description,title,brand,feature,asin,domain
59077,"[Digital Music, Folk]",[],Uncorked,Al Stewart,[],B00B7U613C,Digital_Music
70842,"[Digital Music, Broadway & Vocalists]",[The age of vaudeville. A quartet of penguins ...,"<span id=""parentalAdvisory"" class=""a-size-medi...",Various artists,[],B01433U8MY,Digital_Music

Electronic
(786445, 6)

,category,description,title,brand,feature,asin,domain
231686,"[Electronics, Computers & Accessories, Laptop ...",[Compatible 6-Cell Dell PP39L Battery rated at...,Compatible Dell PP39L Battery,BatteryNerds,[],B0050DU1M4,Electronic
127139,"[Electronics, Computers & Accessories, Compute...",[Office Keyboard],IVR63200 - Office Keyboard,Innovera,"[Batteries Included - No, Batteries Required -...",B0016T3P10,Electronic

Gift_Card
(1542, 6)

,category,description,title,brand,feature,asin,domain
995,"[Gift Cards, Gift Cards]",[Buca di Beppo is the perfect place for great ...,Buca di Beppo Gift Cards - E-mail Delivery,,[],B00MV9EWRU,Gift_Card
944,"[Gift Cards, Gift Cards, No expiration, no fee...",[],Amazon Gift Card - Print - Feliz Cumplea&ntil...,,[],B00JQKK1PE,Gift_Card

Grocery_and_Gourmet_Food
(287051, 6)

,category,description,title,brand,feature,asin,domain
76625,"[Grocery & Gourmet Food, Beverages, Coffee, Te...",[Twinings Of London Pure Peppermint Herbal Tea...,Twinings of London Pure Peppermint Tea K-Cups ...,Twinings,[],B004LL7EZS,Grocery_and_Gourmet_Food
154854,"[Grocery & Gourmet Food, Candy & Chocolate]","[Si usted tiene alguna pregunta, yo hablo espa...",2 X Sanborns Agua De Colonia Clasica Flor De N...,Sanborns,[],B00DXO0QSG,Grocery_and_Gourmet_Food

Home_and_Kitche
(1300540, 6)

,category,description,title,brand,feature,asin,domain
213966,"[Home & Kitchen, Kitchen & Dining, Bakeware, C...",[CK Products chocolate molds are first quality...,CK Products -5/8-Inch Letters/Numbers Chocolat...,CK Products,[Each piece is -5/8-inch by 1/2-inch by 1/8-in...,B003QP36A2,Home_and_Kitche
968012,"[Home & Kitchen, Kitchen & Dining, Kitchen Ute...",[CafePress brings your passions to life with t...,CafePress Scottish Terrier - Obey the Scottie!...,CafePress,[Express yourself with a rectangle magnet desi...,B00VN9PYZI,Home_and_Kitche

Industrial_and_Scientific
(159350, 6)

,category,description,title,brand,feature,asin,domain
59429,"[Industrial & Scientific, Hydraulics, Pneumati...","[<div class=aplus>, This Ideal-Tridon Turn-Key...",Ideal-Tridon Turn-Key Series Stainless Steel 2...,Ideal-Tridon,[],B008Z64HQO,Industrial_and_Scientific
43115,"[Industrial & Scientific, Science Education, S...","[<div class=""aplus"">, The American Educational...",American Educational 15 Piece Fluorescent Mine...,American Educational Products,[],B005QDPT1G,Industrial_and_Scientific

Kindle_Store
(491670, 6)

,category,description,title,brand,feature,asin,domain
333475,"[Kindle Store, Kindle eBooks, Literature & Fic...",[],The Complete History of the Penis - Kindle edi...,Adoni Patrikios,[],B00R6LYK7U,Kindle_Store
192532,"[Kindle Store, Kindle eBooks, History]",[],Lafayette is Here! (Kindle Single) eBook,John Baxter,[],B00EQ2EGSK,Kindle_Store

Luxury_Beauty
Magazine_Subscripti
(2883, 6)

,category,description,title,brand,feature,asin,domain
1897,"[Magazine Subscriptions, Technology, Computers...","[Published since 1994, <I>PC Pro</I> is a Brit...","<span class=""a-size-medium a-color-secondary""",Dennis Publ Ltd/Cust Intreface,[],B00007J7UC,Magazine_Subscripti
1449,"[Magazine Subscriptions, Professional & Educat...","[Intended as continuing education, IFR Refresh...","<span class=""a-size-medium a-color-secondary""",Belvoir Publs Inc,[],B00006KHRK,Magazine_Subscripti

Movies_and_TV
(203541, 6)

,category,description,title,brand,feature,asin,domain
115636,"[Movies & TV, Boxed Sets, Art House & Internat...","[Luis ""Huicho"" Dominguez is a poor, low class,...",El Premio Mayor,Sergio Goyri,[],B001BEK8II,Movies_and_TV
188711,"[Movies & TV, Blu-ray, Movies]",[When Mafuyu Oribe and her adopted sister Tomo...,Qwaser of Stigmata: Complete Collection,Ayumi Fujimura,[],B00NW6KPXQ,Movies_and_TV

Musical_Instrument
(114397, 6)

,category,description,title,brand,feature,asin,domain
57071,"[Musical Instruments, Amplifiers & Effects, Gu...",[Guitar Booster],T-Rex Engineering Crunchy Frog Classic Overdri...,T-Rex Engineering,[],B0064ROWNO,Musical_Instrument
34079,"[Musical Instruments, Instrument Accessories, ...",[Featured in the worlds top selling 4x12 cabin...,"Celestion G12T-75 Guitar Speaker, 8 Ohm",CELESTION,[Built to meet the demands of todays high gain...,B001LOOYP6,Musical_Instrument

Office_Product
(298876, 6)

,category,description,title,brand,feature,asin,domain
78459,"[Office Products, Office & School Supplies, Wr...",[Staedtler Mechanical Pencil Night Blue Series...,"Staedtler Mechanical Pencil Night Blue Series,...",Staedtler,"[Staedtler Mechanical Pencil for Draft, Night ...",B003LOQ790,Office_Product
101108,"[Office Products, Office & School Supplies, De...","[This 8"" round mousepad of the image shown is ...",Titanic Round Mousepad Mouse Pad Great Gift Idea,MYDply,"[Round Mouse Pad (8""), Great gift item. Imprin...",B005DFH7JY,Office_Product

Patio_Lawn_and_Garde
(279456, 6)

,category,description,title,brand,feature,asin,domain
224112,"[Patio, Lawn & Garden, Gardening & Lawn Care, ...",[The Melnor 300 Oscillating Sprinkler With Bra...,Melnor 300 Oscillating Sprinkler With Brass No...,Melnor,[Durable brass jets provide excellent water di...,B010NYVR04,Patio_Lawn_and_Garde
160793,"[Patio, Lawn & Garden, Snow Removal, Snow Shov...","[10"", Deluxe ice chopper/scraper, tempered gal...",SUNCAST SSD9500 10&quot;DLX Ice Chop/Scraper,Suncast,"[This are Putty knives, This are highly durabl...",B00IOX69YG,Patio_Lawn_and_Garde

Pet_Supplie
(189454, 6)

,category,description,title,brand,feature,asin,domain
73753,"[Pet Supplies, Dogs, Toys, Chew Toys]",[JW Pet Company Tough By Nature Bad Cuz Large ...,JW Pet Company Tough By Nature Bad Cuz Large D...,JW Pet,"[Sale JW Pet Company, Rubber Toys]",B00629UDE6,Pet_Supplie
115565,"[Pet Supplies, Dogs, Apparel & Accessories, Ba...",[Celebrate Christmas with this scarf bandana. ...,I See Spot Merry Christmas Dog Pet Bandana Sca...,I See Spot,"[Merry Christmas Holiday bandana, Made of soft...",B00FRRYYLW,Pet_Supplie

Prime_Pantry
Software
(24727, 6)

,category,description,title,brand,feature,asin,domain
23529,"[Software, Education & Reference, Languages]",[Tell Me More v10.5 German 10 Levels will allo...,Rosetta Stone Tell Me More German v10.5,Mongoora,[],B00JPVF88E,Software
3423,"[Software, Photography]","[98/W2K/WME/XP, Ulead PhotoImpact 8 delivers t...",PhotoImpact 8,ULead Systems,[],B000068D9B,Software

Sports_and_Outdoor
(893979, 6)

,category,description,title,brand,feature,asin,domain
154156,"[Sports & Outdoors, Sports & Fitness, Team Spo...",[Crew neck with long sleeve construction. Bio-...,Easton Short Sleeve Enforcer Jacket,Easton,"[Lightweight Batting Shell, Full Range Motion ...",B0032V8WYK,Sports_and_Outdoor
646388,"[Sports & Outdoors, Outdoor Recreation, Water ...","[BIC SUP's new TRACER series (""Touring-Racer"")...",BIC Sport C-TEC Tracer Stand up Paddleboard,BIC Sport,"[TRACER series (""Touring-Racer"") excels as bot...",B00NGDGQ4W,Sports_and_Outdoor

Tools_and_Home_Improvement
(544118, 6)

,category,description,title,brand,feature,asin,domain
568111,"[Tools & Home Improvement, Electrical, Electri...",[<b>* TOOGOO is a registered trademark. ONLY A...,6300-23000RPM DC Motor - TOOGOO(R)6300-23000RP...,TOOGOO(R),"[Product Name : DC Motor, Rated Voltage : DC 3...",B01H01ODFO,Tools_and_Home_Improvement
82079,"[Tools & Home Improvement, Paint, Wall Treatme...",[Interior/Exterior American Accents Aerosol Pa...,"Rust-Oleum 7931830 American Accents Spray, Sat...",Rust-Oleum,"[Smooth satin finish, Can be used outdoors or ...",B0010OKMZ8,Tools_and_Home_Improvement

Toys_and_Game
(571640, 6)

,category,description,title,brand,feature,asin,domain
373585,"[Toys & Games, Kids' Furniture, Dcor & Storage]","[Try a new spin on the ""rocking horse"" with th...",Qaba Kids Plush Rocking Horse-Style Elephant T...,Qaba,"[Comfortably rocks back and forth, Durable lig...",B00GM1KJLG,Toys_and_Game
519521,"[Toys & Games, Baby & Toddler Toys, Bath Toys]",[This listing is for a DC Comics Rubber Duck d...,Dc Comics Superman Rubber Duck with Flashing L...,DC Comics,"[Rubber Duck Dressed as Superman, When pushed ...",B00Z36LL5Y,Toys_and_Game

Video_Game
(82394, 6)

,category,description,title,brand,feature,asin,domain
19483,"[Video Games, Retro Gaming & Microconsoles, Pl...",[<I>Dance Dance Revolution: Disney Mix</I> get...,Dance Dance Revolution: Disney Mix,Konami,[],B00005NCAA,Video_Game
79545,"[Video Games, Accessories]","[1.support: iOS, Android, Windows &amp; Mac OS...",8bitdo F30 Pro Wireless Bluetooth Controller D...,8Bitdo,[FC30 Pro is a bluetooth/USB gamepad professio...,B018K3Q4JY,Video_Game

In [8]:
df = pd.concat(dfs)
df.shape

(13706665, 7)

In [9]:
df.sample(3)

,category,description,title,brand,feature,asin,domain
38560,"[Kindle Store, Kindle eBooks, Health, Fitness ...",[],9 Diet Secrets To Help Women Lose Weight - Kin...,Sarah Benning,[],B005C5Z4PY,Kindle_Store
477817,"[Kindle Store, Kindle eBooks, Science Fiction ...",[],Echoes from Yesterday,Visit Amazon's Sean Benjamin Page,[],B01F2LQEVU,Kindle_Store
238857,"[Electronics, Computers & Accessories, Compute...",[Specifications:<br>\n-Supports SuperSpeed USB...,Koutech EEU330 3.5&quot; SuperSpeed USB 3.0 Ex...,Koutech,[Supports transfer rate at 12Mbps (Full-Speed ...,B00570NYJW,Electronic

## cleanup

### category

In [10]:
%%time
def try2eval(x):
    try:
        x = eval(x)
        x = (o.replace('|','') for o in x)
        return '|'.join(x)
    except SyntaxError:
        return ""

df.category = df.category.astype(str)
df.category = df.category.apply(try2eval)
print("df.shape:", df.shape)

df.shape: (13706665, 7)
CPU times: user 3min 23s, sys: 5.56 s, total: 3min 28s
Wall time: 3min 29s

### text

In [11]:
import re

def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

In [12]:
%%time
df.fillna('', inplace=True)

for col in ['description', 'feature']:
    df[col] = df[col].apply(lambda x: "\n".join(x) if len(x) else "")

for col in ['description', 'title', 'brand', 'feature',]:
    df[col] = df[col].apply(cleanhtml)

CPU times: user 3min 15s, sys: 4.7 s, total: 3min 20s
Wall time: 3min 20s

In [13]:
%%time
df['txt'] = df.title + " " + df.brand + " " + df.description + " " + df.feature

CPU times: user 28.2 s, sys: 8.71 s, total: 36.9 s
Wall time: 36.8 s

# train val split

In [14]:
import numpy as np

np.random.seed(101)
df['is_validation'] = np.random.choice(2, size=len(df), p=[0.85,0.15])

In [15]:
df.is_validation.value_counts()

0    11649852
1     2056813
Name: is_validation, dtype: int64

In [16]:
df.sample(3)

,category,description,title,brand,feature,asin,domain,txt,is_validation
173884,CDs & Vinyl|Alternative Rock|New Wave & Post-P...,VARIOUS ARTISTS - 1980S: MODERN ROCK OF THE 80...,Hardest Hits: Modern Rock of the 80's,Various Artists,,B00009PXXA,CDs_and_Vinyl,Hardest Hits: Modern Rock of the 80's Various ...,0
1251629,"Clothing, Shoes & Jewelry|Women|Shoes|Boots|Kn...",The Aquatalia by Marvin K. collection is manuf...,Aquatalia Women's Helena Dress Boot,Aquatalia,100% Leather\nImported\nSynthetic sole\nShaft ...,B00ISSXHZG,Clothing_Shoes_and_Jewelry,Aquatalia Women's Helena Dress Boot Aquatalia ...,0
934399,"Clothing, Shoes & Jewelry|Women|Contemporary &...",Enjoy all-star footwear from one of the most r...,kate spade new york Women's Cris Pump,,100% Leather\nImported\nLeather sole\nHeel mea...,B00DSLK594,Clothing_Shoes_and_Jewelry,kate spade new york Women's Cris Pump Enjoy a...,0

# save

In [17]:
%%time
df.to_csv(f'../data/data__{prfx}.csv', index=False)

CPU times: user 8min 18s, sys: 29.9 s, total: 8min 48s
Wall time: 8min 49s

In [18]:
ls -hl ../data/data__{prfx}.csv

-rw-rw-r-- 1 ubuntu ubuntu 22G Mar  5 02:23 ../data/data__prep_20210304A1.csv

## make a sample

In [19]:
import numpy as np
np.random.seed(101)
df_sample = df.sample(10000)

In [20]:
df_sample.to_csv(f'../data/data_sample__{prfx}.csv', index=False)

## make more samples

In [3]:
%%time
df = pd.read_csv(f'../data/data__{prfx}.csv')

<string>:2: DtypeWarning: Columns (1,2,3,4,5,6,7) have mixed types.Specify dtype option on import or set low_memory=False.

CPU times: user 3min 4s, sys: 24.5 s, total: 3min 28s
Wall time: 4min 57s

In [4]:
len(df)

(14688205, 9)

In [5]:
for sz in (int(o) for o in (1e4, 1e5, 1e6, 5e6)):
    df_sample = df.sample(sz)
    df_sample.to_csv(f'../data/data_sample_{sz}__{prfx}.csv', index=False)